version: '2.1'

services:
  ecommerce-mysql:
    image: mysql:5.7.28
    container_name: ecommerce-mysql
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root#local
      - TZ=Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
